spring:
  servlet:

    multipart:
      max-file-size: 500MB
      max-request-size: 2000MB
  datasource:
    url: jdbc:mysql://114.55.0.204:3306/compare
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: compare
    password: compare
  resources:
    static-locations: classpath:/static/
  redis:
    host: 114.55.0.204
    port: 6379
    password: nosugar
    lettuce:
      pool:
        max-active: 20



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8081



alipay:
  url: https://openapi.alipaydev.com/gateway.do
  appid: 2021000119649956
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCwTQOgx6L71BKqaPC1M8PrZRa/WPfJp72eTkZugyQvERUCJ5p8etEXZUJLoHtz0gzAd+jEY+jJsLA8uZffbsfFXpJl+WgE81yAtcoCmALdp6v1RLZb3EhVLYa/8YMNA0HPvzj0IEh+jEBLgjnjM2b1vs/wetYjoWyt5Ce6Qe+hiNtsYVzKlFxsQsTy4mTnrjvwjxvRkECXzV4p1jUO44OSv5UfUQ3ROqAYG7SD1Ak+xwVsY9R7ZwkzFieaMKu8R7m5NWSRt5s0kWUsOTcZVxthl2eW4FCNw+7f28Kpxahw+GzjN9aaa0f0rzHw1MOY0Y1Y2Ku0WfSG+ZzGb4srF2snAgMBAAECggEAK8rFhu9v7avNAyVT/T6hgNw4XUllK2MON79rwVGz8DkHBeT+e8MqIuyVHiH76FYZsslWOUoz7b2E2WCkd+yVlNIb/VaJXwlwRcxiJGjL9XELxr3Nql26XeYUHaOJEPdpJohyRjmqqDyAUAFGDcib35kJH8vzWyBi1YLh12M/edkQtFdCSpWOxZh0juJWjsSyoAe0qeGeslqSPvnhS1WOcbr4/YIcO5MF28vKik8tfoVLikTgDL85ef9sNozGfr1Y3z7GVgKJkfiR28YzN5Q9qdEywqnOz0pOrvwZ9+10JuIFB8nuEXYqR6WNLnABkmlgZW9tG0JLVC8EzjZhwesUuQKBgQD9MM+YiJEoq0iVCdmtpesWlA4lPdxleDXkYGgJE3YVmOt0cP6mrBwcaAddBIwl/NR60nEw1jggT9H2L+on3Q7afyGTC9VzZs3nbqMpyjLZQqsGRoMmuRXQzvNLZFOiBn+j2R0A6UP4Dg/FSpgtw9GkgwrlJbLwFJlRry9vYK2k9QKBgQCyQcwhe5ZDml3u8RZX2M3teefgpV+2xAw26YZShc0Lu4A0HEZkegDBIZwAuILo4F9MykhG3nvSLR3BgsrIshNvXC0szH6B/7TebtiilOzqWrMA3rBkfIUCuuQ0d7rVjPSspEfwQy3z1FISbkQB+L7CuAWgBK8PSkET69AYIzgeKwKBgDdrXLVNh0B4pW2B93Sr8ZZCmAoMzVYkht9TPtJlwR4fF8KoDQVcfNa26o2wtiCGg9fSglYnPafM8O9LM5zAJUUsOKQgHfuhkAZNUEeQa6rkjdzUyFZMgvruoZBqCGhZtcyedFvDs03zff44QrEZwKSazmKz6sPkLl8T0nU1myyVAoGATg9IL+Vp4QLJXahPi3qSewrmQtbIekWRv741pw+WwiuCsc8r+DYA/JIWOa6TDR2sPfla+0XUXS6KmEIJQSfSIPLxiWunfpAWiU1rKo8izGGZf6kE/4wTxyVGZ7+Cnp+SScPLCOiyR9NTeWS1/VMLXkOtmuxSKNTweKPMRbWujm8CgYBn71Gr1kuj5rs4iS5V7Wmd5Z0rkamp13FJrXKAIZshn0nkJ4OY94GIhl/5qsPHkZCmZa/HE9UcgffoYxhQKFbisZl7EmX90izYwWefvXKE2wG20znWJyr/7IS33Tc4HRji1YkE1OO6NuJgSHU9erUQz3BTS+Vreppsh+XGB2H0eQ==
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn31c2cJ0nuDEwQR/5kOsjq5bjgG2bRYG6URKVlQBISXFPvnGE6zV+QiTHChPAzxu/L8k3BpV1uWR1CwGY1MWQgsnTZomxPEuG/BHI6Cd/zuIw/uWvUTmnogfqgsBTzWuSjY0Vm3tQf+BMjrU+6dDFh/nz5nICoL8CMRblWGIgY9zRg1Wrm3fsK1nHTsRe4aces6xtbMlmYK5sqmUaHy84Gtgs0r2Sl4L6hsGF6amlWEMrdDGP5Qs07p0lRr2wlEib3b4P+72uoNepEY56DLnBuctTkfBbt83iEAhLtA6L1g/Fdm+j5MprL8rxtQQXjpXYAcM5kJ0ZPjOB9JH7t28zwIDAQAB
  notifyUrl: http://buchitang.top:8081/order-log/notify
  returnUrl: http://buchitang.top:8081/succeed



